apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-maven-app
  labels:
     app: java-maven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-maven-app
  template:
    metadata:
      labels:
        app: java-maven-app
    spec:
      imagePullSecrets:
      - name: docker-key
      containers:
      - name: sample-ctr
        image: devopstrainer/java-mvn-privaterepos:$BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc1
  labels:
      app: java-maven-app
spec:
  selector:
    app: java-maven-app
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
