AWSTemplateFormatVersion: 2010-09-09
Description: stagging environment

Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-031af4f81d8b809a9
      InstanceType: t2.micro
      IamInstanceProfile: 
       - Type: AWS::IAM::InstanceProfile
         Properties: 
           Roles: 
            - "cloudformation"
      KeyName: awskey
      SecurityGroupIds: 
       - 
        Ref: "WebServerSecurityGroup"
      Tags:
        - 
          Key: Name
          Value: 
           - 
            Fn::Sub: '${AWS::StackName}-WebServer'
        - 
          Key: environment
          Value: stagging
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: security group for web servers
      SecurityGroupIngress:
        - 
          IpProtocol: "tcp"
          FromPort: 8080
          ToPort: 8080
          CidrIp: "0.0.0.0/0"
        - 
          IpProtocol: -1
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"         
Outputs:
  WebServerDnsName:
    Value: !GetAtt WebServerInstance.PublicDnsName
    Description: Public DNS name of the web server instance