AWSTemplateFormatVersion: 2010-09-09
Description: stagging environment

Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-031af4f81d8b809a9
      InstanceType: t2.micro
      KeyName: awskey